### ISSUE TITLE
Рефакторинг FiniteAutomaton::to_regex

### ISSUE THREAD

**Issue by AngelicHedgehog** [OnionGrief/Chipollino#279]
## Требуется провести рефакторинг кода метода [_to_regex_](https://github.com/OnionGrief/Chipollino/blob/main/libs/Objects/src/FiniteAutomaton.cpp#L2447) класса _FiniteAutomaton_.

Задание выдано в рамках программы искусственного улучшения успеваемости по ТФЯ

**Comment by xendalm** [comment]
Рекомендую отпочковаться от этой ветки, чтобы потом мы не решали конфликты https://github.com/OnionGrief/Chipollino/tree/fa-regex-refactoring
