### ISSUE TITLE
Создание нормальных unit тестов

### ISSUE THREAD

**Issue by dak151449** [OnionGrief/Chipollino#283]

**Comment by TonitaN** [comment]
Мы включаем только тестирование на константных данных (обычные юнит-тесты) или добавляем метаморфное (т.е. на леммах и случайных регексах)? И если да (я нашла один метаморфный тест в модуле, но только для парсера, и его даже можно будет потом усилить, т.к. по факту там больше, чем эквивалентность, а ещё и равенство по модулю ассоциативности), то условимся как-нибудь различать их оформление?

P.S. - Да, я только на PSSV узнала, что оказывается, тестирование на леммах, которое мы тут активно практикуем уже год, называется метаморфным:
https://en.wikipedia.org/wiki/Metamorphic_testing

**Comment by dak151449** [comment]
> Мы включаем только тестирование на константных данных (обычные юнит-тесты) или добавляем метаморфное (т.е. на леммах и случайных регексах)? И если да (я нашла один метаморфный тест в модуле, но только для парсера, и его даже можно будет потом усилить, т.к. по факту там больше, чем эквивалентность, а ещё и равенство по модулю ассоциативности), то условимся как-нибудь различать их оформление?
> 
> P.S. - Да, я только на PSSV узнала, что оказывается, тестирование на леммах, которое мы тут активно практикуем уже год, называется метаморфным: https://en.wikipedia.org/wiki/Metamorphic_testing

Добавил разделение тестов, теперь это разные App при сборке. Unit тесты останутся "обычными", а MT будут добавляться внутри MetamorphicTestsApp.
