### ISSUE TITLE
Преобразования в классе MFA

### ISSUE THREAD

**Issue by xendalm** [OnionGrief/Chipollino#287]
- [x] Парсинг #311
- [x] Equal #305
- [x] IsDeterministic
- [x] AddTrapState
- [x] Complement
- [x] RemoveEps

**Comment by TonitaN** [comment]
С `Reverse` у нас непростая история: реверсируется-то регулярка, то есть это метод для b-regex. 

Про детерминизм: есть два понятия - по Шмиду (если есть переходы по памяти, то нет никаких других) и по семантике (если по памяти первые буквы отличаются от имеющихся на других переходах, то детерминизм считаем выполненным). Первый допускает добавление ловушки, и поэтому можно делать дополнения. Семантический 1-детерминизм уже не так дружит с ловушками. Предлагаю оставить предикат Deterministic для понятия по Шмиду, а для 1-детерминизма по семантике перегрузить SemDet.
