### ISSUE TITLE
Баг преобразования arden

### ISSUE THREAD

**Issue by AngelicHedgehog** [OnionGrief/Chipollino#307]
В случае, если исходный автомат не является конечным, выбрасывается `segmentation fault`

Пример:
![image](https://github.com/OnionGrief/Chipollino/assets/102258145/417654f7-d941-4bec-b134-4aa61bc25f86)

**Comment by xendalm** [comment]
Исправить, конечно, полезно... Но есть подозрение, что многие методы не будут работать на таком автомате)
